### PR TITLE
Feat/2018 login

### PR DESCRIPTION
**Pull request by jazinheira**
@rpmcdonnell What do you think of the login page? Anything that needs to change? Don't worry about the exact wording; we have to change that in the language strings on the server.

### CODE REVIEW

**Comment by rpmcdonnell** [comment]
I think rounding box corners, larger "Create new Account" box

**Comment by rpmcdonnell** [comment]
Changed the Background color and added rounded edges

**Comment by jazinheira** [comment]
@rpmcdonnell  Ignoring the rounded buttons (we'll do that in another branch) how is the sizing now?

screen shot 2018-09-07 at 10 50 49 am

**Comment by jazinheira** [comment]
Updated the image position.
screen shot 2018-09-11 at 6 46 04 pm

**Comment by jazinheira** [comment]
@rpmcdonnell Can you lower the position of the water a bit more and increase the overall image height more?

**Pull request merged**
