### PR TITLE
Feat/2018 footer

### PR DESCRIPTION
**Pull request by jazinheira**
This creates our custom footer. @rpmcdonnell can you have a look at it and attach some screenshots?

### CODE REVIEW

**Comment by rpmcdonnell** [comment]
Only issue is with small width when the icons go to the bottom. 
footer - mobile

**Comment by jazinheira** [comment]
Hmm what's the issue there? Only the size?

**Comment by rpmcdonnell** [comment]
Yeah, was just thinking have them be slightly less tall, maybe 5 pixel height difference, but it's not necessary

**Comment by jazinheira** [comment]
Ok, check it out now @rpmcdonnell

**Pull request merged**
