### PR TITLE
Styling for call to action block that will display to guests.

### PR DESCRIPTION
**Pull request by dta121**
image

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1201412162419969

### CODE REVIEW

**Comment by rpmcdonnell** [comment]
Icon could be about 30% smaller when applied to the Course pages in particular, other than that looks good

**Comment by jazinheira** [comment]
Nice work, I think with a few tweaks we can make this even more helpful!

1) Technically, you should add more specificity to the CSS. Some of this CSS will be picked up in other places and cause unintentional styling. For example:

```
.action-blocks .card-icon {}
```
Small style note: make the class 'action-block' since it's singular.

2) Let's also set the size for the icons using the fontawesome/bootstrap classes. This should let it size more appropriately based on the text and screen sizes. https://fontawesome.com/v6.0/docs/web/style/size

---

On the content side:
- Should we remove the large banner on the frontpage? It's serving the same purpose as the text in the action block and making the course list show up below the fold on a lot of screens.
- We should change the text slightly for each page type to be more specific. On the frontpage, we can say something like "Check out some of courses below and start learning by signing up. ['Log in or Sign Up' button]". We should also have links in the text to go back to the certificates and credit pages, so they can be placed in our normal flow/get more info. On the course page action blocks, we can talk about the full course list in our catalog instead.
- On the course page action block CTA, we should make that more specific - "Click here" is pretty generic. "View course catalog" or "View all courses" or something along those lines.
- Outside of the actual front/course catalog page, we shouldn't have the 'Course Catalog' header. It's confusing seeing that inside a course - makes it look like that page is the course catalog.
- Course Categories: we could use the same block as the in course action block?

**Comment by rpmcdonnell** [comment]
Yeah i really like the basis of this, and it's super helpful as a more general tool, but as it applies to the aforementioned pages turned de-facto landing pages, i've been working on a document to help clarify the project requirements to outside people and typed up the copy versions here: https://docs.google.com/document/d/1-OKVnyyd1V-M0uz3dzge-519ab8yxPSX6PC_NmJF0ek/edit

**Comment by jazinheira** [comment]
Looking good! I think we need to reduce the size of icon and some of the whitespacing in the box, especially on smaller screen sizes, so that the content isn't pushed down so far down below the fold. Let's make the icon something like 2x and 3rem on small screens.

Something like this:

image

**Comment by dta121** [comment]
image

**Comment by jazinheira** [comment]
Ok, with the corresponding bootstrap class modifications in the block itself, looks good! :confetti_ball:

**Review by jazinheira — APPROVED** [review]

**Pull request merged**
