### PR TITLE
Changing the fontawesome size for mobile

### PR DESCRIPTION
**Pull request by dta121**

### CODE REVIEW

**Comment by dta121** [comment]
image

**Comment by dta121** [comment]
Fix the screen size for larger screens

image

**Review by jazinheira — CHANGES_REQUESTED** [review]
Did setting the justify-content-center not work? If we do end up having a larger screen this won't allow us to have any blocks on the right!

If we do need to make this a column, you should set that in the bootstrap classes - you can use flex-lg-column to make large screens and up a column. The lg modifier is for screens >= 992px and xl is for >=1200px by width.

You want to use the bootstrap stuff if possible, and shy away from media queries unless *absolutely* necessary. They have a tendency to break layouts in odd ways with multiple media queries.

**Review by jazinheira — APPROVED** [review]
Much better!

**Pull request merged**
