### PR TITLE
Change login greeting messages

### PR DESCRIPTION
**Pull request by jazinheira**
Change guest access log in text, not logged in login text, and logged in greeting text.

@sharmi55 We want to make "Log in or Sign up" bigger?

screen shot 2017-09-12 at 5 50 54 pm
screen shot 2017-09-12 at 5 30 39 pm

### CODE REVIEW

**Comment by sharmi55** [comment]
@jazinheira since I can't really tell the proportions from the screen cap, I would suggest we leave it as in for now. I can easily change it later.

**Comment by jazinheira** [comment]
@sharmi55 check it out in the vm when you get a chance!

**Comment by sharmi55** [comment]
I've change the font size:

before:

screen shot 2017-09-18 at 3 23 44 pm

after:

screen shot 2017-09-18 at 3 25 15 pm

@jazinheira Please check my work before merging.

**Comment by jazinheira** [comment]
Good job! @sharmi55

**Pull request merged**
