### PR TITLE
Adding top and internal top block layout to course catalog

### PR DESCRIPTION
**Pull request by dta121**
Adding the block top and internal top area to the course catalog page so the action block can appear in the correct position.

### CODE REVIEW

**Review by jazinheira — CHANGES_REQUESTED** [review]
Cool thanks for getting to this! Two changes:

1) Make sure to update the regions in config.php for coursecategory pages, or else we won't have the option to put a block there! Notice top and top-interior in the frontpage declaration:
```
    'frontpage' => array(
        'file' => 'frontpage.php',
        'regions' => array('side-pre', 'top', 'top-interior'),
        'defaultregion' => 'side-pre',
        'options' => array('nonavbar' => true),
    ),
```

2) Looks like this will put the top interior block **above** the banner. I think that it would look better for those to be beneath the category banner.

**Comment by dta121** [comment]
image

**Comment by jazinheira** [comment]
@dta121 Top interior? How does a block look there?

**Comment by dta121** [comment]
image

**Comment by dta121** [comment]
image

**Comment by dta121** [comment]
image

**Comment by dta121** [comment]
Made the border darker in the dashboard page 

image

**Review by jazinheira — APPROVED** [review]
Yes! Looking good :shipit:

**Pull request merged**
