### PR TITLE
Feat/fix padding

### PR DESCRIPTION
**Pull request by sharmi55**
@ja please note the identified issues: Fix padding #21 and how I've solved them via quick-fix on custom.css.

### CODE REVIEW

**Comment by jazinheira** [comment]
I noticed that this fixed left padding in nav blocks. However, there's no top padding still - were you trying to add some?

**Comment by jazinheira** [comment]
@sharmi55

**Comment by jazinheira** [comment]
So there seems to be some weird amount of padding on the headers (is it h2?) used in the side blocks(this was true before the latest padding commit and is present on learn):

screen shot 2017-07-07 at 5 17 51 pm

There's also more padding under the content now than above:
screen shot 2017-07-07 at 5 19 57 pm

It probably was fine before, right? Are you seeing something different?
screen shot 2017-07-07 at 5 23 01 pm

**Comment by sharmi55** [comment]
@jazinheira I'll fix it now

**Comment by jazinheira** [comment]
Just tested and there's no change in regards to the vertical padding - left padding on the header is gone again. I looked into the CSS and there's another '.block .content' statement that's overriding the one you added with 20px of padding on top and bottom; that's causing the weird header spacing. Be sure to look that there aren't other statements affecting classes!

Please test locally before committing.

 There's too much back and forth on this branch - we should start over. One commit for the vertical padding, one commit for the left padding, done. Different branch to remove enrolment icons.

**Comment by sharmi55** [comment]
Agreed for creating new branches. Will do it today.

I couldn't test locally since my VM wasn't working but will try out solution of updating plugins. Thanks!

**Pull request closed without merging**
