### PR TITLE
Feat/add html parser live syntax checking

### PR DESCRIPTION
**Pull request by jazinheira**
This update to the html parser questions:

1) Set the font size to be consistent between all editors - 16pt
2) Enables autocompletion/checking. There's a little box that alerts someone that syntax is off.

image

### CODE REVIEW

**Review by dta121 — COMMENTED** [review]
I double checked to make sure I loaded the correct branch on my sandbox, but when I looked at a coderunner question, it only showed the HTML area as having 16pt. The CSS and JS area didn't get the style attribute. When I checked the inspector, it only showed it for HTML and not CSS or JS. I don't know if it's on my end or if something is off. Here's a screenshot to show you what I mean 
image

**Comment by jazinheira** [comment]
Thanks for looking into that so quickly. That is interesting... could you try to purge your caches again? It's a pure JS change so without regenerating the cache it won't be picked up.

**Comment by dta121** [comment]
Ok, did that and something did change. The font size are now the same in all three text editor areas, but the syntax highlight that showed up the first time is now gone and is just black.

image

**Comment by dta121** [comment]
Everything on dev looks good.
image

**Pull request merged**
